targets:
  $default:
    builders:
      string_utils_generator:
        enabled: true

builders:
  string_utils_generator:
    import: "package:string_utils_generator/string_utils_generator.dart"
    builder_factories: ["stringUtilsBuilder"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    runs_before: [source_gen]
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
